# Generated by Django 5.0.3 on 2024-05-23 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wowsite', '0002_wowclass'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wowclass',
            options={'ordering': ['title']},
        ),
        migrations.AddField(
            model_name='wowclass',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=20),
        ),
    ]
