# Generated by Django 5.0.3 on 2024-05-23 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wowsite', '0003_alter_wowclass_options_wowclass_slug'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='wowclass',
            index=models.Index(fields=['created'], name='wowsite_wow_created_2a107e_idx'),
        ),
    ]
