# Generated by Django 5.0.3 on 2024-05-23 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wowsite', '0004_wowclass_wowsite_wow_created_2a107e_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wowclass',
            name='slug',
            field=models.SlugField(max_length=20, unique=True),
        ),
    ]
