# Generated by Django 5.0.3 on 2024-05-23 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wowsite', '0006_alter_wowclass_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wowclass',
            options={'ordering': ['created']},
        ),
        migrations.RemoveIndex(
            model_name='wowclass',
            name='wowsite_wow_created_1087ee_idx',
        ),
        migrations.AddIndex(
            model_name='wowclass',
            index=models.Index(fields=['created'], name='wowsite_wow_created_2a107e_idx'),
        ),
    ]
