# Generated by Django 5.0.3 on 2024-05-24 12:27

import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wowsite', '0007_alter_wowclass_options_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='wowclass',
            managers=[
                ('published', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='wowclass',
            name='is_published',
            field=models.BooleanField(choices=[(0, 'Чорновик'), (1, 'Published')], default=0),
        ),
    ]
