# Generated by Django 5.0.3 on 2024-05-25 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wowsite', '0008_alter_wowclass_managers_alter_wowclass_is_published'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=10)),
                ('slug', models.SlugField(max_length=10, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='wowclass',
            name='roles',
            field=models.ManyToManyField(blank=True, related_name='roles', to='wowsite.role'),
        ),
        migrations.CreateModel(
            name='Specialization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('description', models.TextField(blank=True)),
                ('slug', models.SlugField(max_length=30, unique=True)),
                ('role', models.ForeignKey(default='Undefined', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='role', to='wowsite.role')),
                ('wow_class', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='wow_class', to='wowsite.wowclass')),
            ],
        ),
    ]
