# Generated by Django 5.0.3 on 2024-05-25 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wowsite', '0009_role_wowclass_roles_specialization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialization',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='specialization',
            name='role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='role', to='wowsite.role'),
        ),
        migrations.AlterField(
            model_name='specialization',
            name='wow_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wow_class', to='wowsite.wowclass'),
        ),
        migrations.AlterField(
            model_name='wowclass',
            name='roles',
            field=models.ManyToManyField(related_name='roles', to='wowsite.role'),
        ),
    ]
