# Generated by Django 5.0.3 on 2024-05-30 18:42

import taggit.managers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        ('wowsite', '0010_alter_specialization_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wowclass',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
