# Generated by Django 5.0.3 on 2024-06-30 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wowsite', '0012_alter_role_options_alter_specialization_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='title',
            field=models.CharField(db_index=True, max_length=10, verbose_name='Назва ролі'),
        ),
        migrations.AlterField(
            model_name='specialization',
            name='title',
            field=models.CharField(max_length=30, verbose_name='Назва спеку'),
        ),
        migrations.AlterField(
            model_name='wowclass',
            name='title',
            field=models.CharField(max_length=30, verbose_name='Назва класу'),
        ),
    ]
