# Generated by Django 5.0.3 on 2024-07-05 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wowsite', '0014_menu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wowclass',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='Slug'),
        ),
    ]
