# Generated by Django 5.0.3 on 2024-07-28 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wowsite', '0015_alter_wowclass_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='specialization',
            options={'ordering': ['wow_class'], 'verbose_name': 'Спеціалізації', 'verbose_name_plural': 'Спеціалізації'},
        ),
        migrations.AlterField(
            model_name='menu',
            name='slug',
            field=models.SlugField(max_length=20, unique=True),
        ),
    ]
